[package]
name = "fift-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fift = "0.1"
js-sys = "0.3"
wasm-bindgen = { version = "0.2", features = [] }

getrandom = { version = "0.2", features = ["js"] }
